spring:
  profiles:
    active: local
  devtools:
    add-properties: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    
zoom:
  metadata:
    clientId: N_OdC7USTPqQt0pNgOJc2w
    clientSecret: EyPBrYz0nYEM9oW41Abe99q6Zdnjme9A
    oauthTokenStorageCollection: oauthTokens
    oauthTokenStorageDocument: active

swagger:
  metadata:
    title: Zoom Connect
    description: API's to interact with Zoom Connect
    version: 0.0.1