spring:
  profiles:
    active: local
  devtools:
    add-properties: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    
zoom:
  metadata:
    serverUrl: https://api.zoom.us/v2
    userId: prashanthcharla1212@gmail.com
    clientId: el6yuXN6S4qZAm3ejwrdqg
    clientSecret: bZZnYGvobrk14977kVWpusbygw4V8ing
    oauthTokenStorageCollection: oauthTokens
    oauthTokenStorageDocument: active
    createdMeetingsStorageCollection: createdMeetings

swagger:
  metadata:
    title: Zoom Connect
    description: API's to interact with Zoom Connect
    version: 0.0.1